import jsPDF from "jspdf";

import headerImg from "@assets/pdf_headers/receipts_pdf_header.png";

  const doc = new jsPDF();
  let y = 10;

  // Add header image (logo + text) from local assets, scaled and as JPEG for smaller size
  doc.addImage(headerImg, "JPEG", 20, y, 170, 20);
  y += 25;

  // Consolidated generateReceiptPDF function
export function generateReceiptPDF(receipt: any) {
  const doc = new jsPDF();
  let y = 0;

  // Make header image cover the full width of the page
  const pageWidth = doc.internal.pageSize.getWidth();
  const headerHeight = 60;
  doc.addImage(headerImg, "JPEG", 0, y, pageWidth, headerHeight);
  y += headerHeight + 5;

  // Top left info section (Date and Generated by)
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  
  const generatedBy = receipt.created_by_name || "System";
  const createdDate = receipt.created_at ? new Date(receipt.created_at).toLocaleDateString() : new Date().toLocaleDateString();
  
  doc.text(`Date: ${receipt.date || createdDate}`, 20, y);
  doc.text(`Generated by: ${generatedBy}`, 20, y + 8);
  y += 25;

  // Receipt details in the reference style (removed RECEIPT title)
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);

  // Receipt Number
  doc.text(`Rec No.  :  ${receipt.receipt_number || "-"}`, 20, y);
  y += 10;

  // Received from / Paid to
  const fromTo = receipt.received_from || receipt.paid_to || "-";
  doc.text(`${receipt.received_from ? 'Received from' : 'Paid to'}  :  ${fromTo}`, 20, y);
  y += 15;

  // Amount in words
  doc.text(`Payment Method: `, 20, y);
  y += 15;

  // Payment method checkboxes - smaller and better aligned
  const paymentMethods = ['Cash', 'M-pesa', 'Cheque', 'Card', 'Bank Transfer'];
  const selectedMethod = receipt.payment_method_display || receipt.payment_method || 'Cash';
  
  let checkboxX = 20;
  doc.setLineWidth(0.5);
  paymentMethods.forEach((method) => {
    // Draw smaller checkbox (4x4 instead of 8x8)
    doc.rect(checkboxX, y - 6, 4, 4);
    if (selectedMethod.toLowerCase().includes(method.toLowerCase()) || 
        (method === 'Cash' && selectedMethod === 'CSH')) {
      // Draw smaller checkmark
      doc.setLineWidth(1);
      doc.line(checkboxX + 1, y - 4, checkboxX + 2, y - 3);
      doc.line(checkboxX + 2, y - 3, checkboxX + 3, y - 5);
      doc.setLineWidth(0.5);
    }
    doc.text(method, checkboxX + 8, y - 3);
    checkboxX += method.length * 3.5 + 20;
  });
  y += 15;

  // Payment Reference line - better aligned
  doc.text('Payment Reference:', 20, y);
  doc.line(95, y + 2, 180, y + 2);
  if (receipt.payment_reference) {
    doc.text(receipt.payment_reference, 97, y);
  }
  y += 20;

  // Purpose section
  doc.text(`For the purpose of  :  ${receipt.purpose || "Rent"}`, 20, y);
  y += 15;

  // Amount section - clean underlined format instead of box
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text('Amount:', 20, y);
  doc.setFontSize(16);
  doc.text(`Ksh ${receipt.amount || "0"}`, 80, y);
  doc.setLineWidth(1);
  doc.line(80, y + 3, 150, y + 3);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  
  y += 25;

  // Signature sections with thinner lines
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.setLineWidth(0.5);
  
  // Received By section
//   doc.text('Received By', 30, y);
//   doc.line(20, y + 10, 90, y + 10);
  
//   // Signature section  
//   doc.text('Signature', 130, y);
//   doc.line(120, y + 10, 190, y + 10);
  
  y += 25;

  // Compact footer design with header colors - reduced height by 40%
  const footerStartY = doc.internal.pageSize.getHeight() - 36; // Reduced from 60 to 36
  const footerPageWidth = doc.internal.pageSize.getWidth();
  
  // Blue and orange footer background matching header
  doc.setFillColor(0,34,95); // Blue from header
  doc.rect(0, footerStartY, footerPageWidth, 36, 'F');
  
  // Orange geometric accent
  doc.setFillColor(255, 165, 0); // Orange
  doc.triangle(0, footerStartY, 0, footerStartY + 36, 24, footerStartY + 36);
  doc.triangle(footerPageWidth - 24, footerStartY, footerPageWidth, footerStartY, footerPageWidth, footerStartY + 24);
  
  // Simple footer text
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("AQAL MANAGEMENT SOLUTIONS", 105, footerStartY + 15, { align: "center" });
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Professional Property Management Services", 105, footerStartY + 25, { align: "center" });

  // Save PDF
  doc.save(`${receipt.receipt_number || "receipt"}.pdf`);
}
